"""initial_schema

Revision ID: 8119cb1b5f82
Revises:
Create Date: 2025-12-17 17:13:50.787460

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import os

# Try to import pgvector, but make it optional
try:
    import pgvector.sqlalchemy.vector
    HAS_PGVECTOR = True
except ImportError:
    HAS_PGVECTOR = False


# revision identifiers, used by Alembic.
revision: str = '8119cb1b5f82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector extension removed - not available on Railway
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_slug'), 'funds', ['slug'], unique=True)
    op.create_table('portfolio_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('hq_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_companies_name'), 'portfolio_companies', ['name'], unique=False)
    op.create_table('stealth_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detected_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stealth_detections_fund_slug'), 'stealth_detections', ['fund_slug'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('round_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_usd', sa.Integer(), nullable=True),
    sa.Column('valuation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('is_lead_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('thesis_drift_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['portfolio_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_fund_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('raw_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),  # JSON string when pgvector unavailable
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.create_table('deal_investors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('investor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('is_tracked_fund', sa.Boolean(), nullable=False),
    sa.Column('partner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_drift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('sector_embedding', sa.Text(), nullable=True),  # JSON string when pgvector unavailable
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_drift_fund_slug'), 'thesis_drift', ['fund_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_drift_fund_slug'), table_name='thesis_drift')
    op.drop_table('thesis_drift')
    op.drop_table('deal_investors')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_table('articles')
    op.drop_table('partners')
    op.drop_table('deals')
    op.drop_index(op.f('ix_stealth_detections_fund_slug'), table_name='stealth_detections')
    op.drop_table('stealth_detections')
    op.drop_index(op.f('ix_portfolio_companies_name'), table_name='portfolio_companies')
    op.drop_table('portfolio_companies')
    op.drop_index(op.f('ix_funds_slug'), table_name='funds')
    op.drop_table('funds')
    # ### end Alembic commands ###
